require "yogi.keymaps"
require "yogi.options"
require "yogi.plugins"
require "yogi.Masonlspconfig"
require "yogi.pluginconfigs.colorscheme"
require "yogi.pluginconfigs.cmp"
require "yogi.pluginconfigs.nvim-tree"
require 'nvim-tree'.setup {}
require "yogi.pluginconfigs.telescope"
require "yogi.pluginconfigs.bufferline"
require "yogi.pluginconfigs.autopairs"
require "yogi.pluginconfigs.autocommands"
require "yogi.pluginconfigs.lualine"
require "yogi.pluginconfigs.treesitter"
require "yogi.pluginconfigs.comment"
require "yogi.pluginconfigs.cmp"
